name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN:
      SENTRY_ENVIRONMENT: ci
      PORT: 5000
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🧪 Run test script
        run: npm test
